apiVersion: v1
kind: Service
metadata:
  name: &service-name m-bff
spec:
  type: ClusterIP
  selector:
    app: *service-name
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP